name: build and test code

on:
  push:
    branches:
      - "**" # matches every branch

jobs:
  build-extension:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19.1.0"
      - run: npm install
        working-directory: extension
      - run: npm run build
        working-directory: extension

  test-api:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        working-directory: api
      - name: Test with pytest
        run: |
          pytest
        working-directory: api
